spring.application.name=paqueteria
spring.datasource.url=jdbc:postgresql://localhost:5433/paqueteria_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jakarta.persistence.jdbc.url=jdbc:postgresql://localhost:5433/paqueteria_db
jakarta.persistence.jdbc.driver=org.postgresql.Driver